services:
  - type: web
    name: snipclip
    env: node
    buildCommand: npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free 